### ISSUE TITLE
Path with highest cost

### ISSUE THREAD

**Issue by Turbo87** [albertorestifo/node-dijkstra#19]
Is it possible to use this library to find the path from A to B with the highest cost, instead of the lowest? I thought I could just use negative numbers everywhere, but the cost validation apparently isn't allowing that. I could use `1000000 - actualCost` as the cost value and it seems to work but I'm wondering if there maybe is a better solution for this problem that I'm missing. 🤔

**Comment by albertorestifo** [comment]
No, it's not possible as the Dijkstra algorithm is specifically optimized to discard expensive paths as soon as possible, without ever visiting them.

The cost of the nodes can't be negative as it would completely break the algorithm. Moreover, the cost should be some factor of distance between the nodes. A negative cost just doesn't make any sense.

Maybe you can get away with it just by modifying the [`PriorityQueue#sort`](https://github.com/albertorestifo/node-dijkstra/blob/master/libs/PriorityQueue.js#L29) to order the nodes with the most expensive node first. However, it's very likely that more changes are needed and the algorithm will become very slow. Another place that might require modification is [here](https://github.com/albertorestifo/node-dijkstra/blob/master/libs/Graph.js#L240).

My conclusion? The Dijkstra algorithm is specifically built for searching the shorted path as efficiently as possible. Using it to find the longest route, would be like using a screwdriver to plant a nail. It's just not the right tool for the job.
