### ISSUE TITLE
change weight

### ISSUE THREAD

**Issue by tahnaconus** [albertorestifo/node-dijkstra#21]
hello, your library is very helpful. When using it i want to change weight of path ,but i don't know how to change value of addNode with json object. Could you possibly help me use this? many thanks

**Comment by albertorestifo** [comment]
The easiest approach is to remove the node you want to update and then add it again.

For example:

Given this starting graph:

```js
const Graph = require('node-dijkstra')

const route = new Graph()

route.addNode('A', { B:1 })
  .addNode('B', { A:1, C:2, D: 4 })
  .addNode('C', { B:2, D:1 })
```

If I then want to update B, I would do:

```js
route.removeNode('B')
  .addNode('B', { A:3, C:4, D:2 })
```
