### ISSUE TITLE
Find all shortest paths

### ISSUE THREAD

**Issue by retorquere** [albertorestifo/node-dijkstra#28]
Is it possible to return all shortest paths in the case that there is more than one path with the same (minimal) cost?

**Comment by albertorestifo** [comment]
I can't think of any easy way.

Given that this implementation uses a couple of optimizations to be the fastest possible, it never attempts to calculate any second paths, it exclusively considers the first least-costly path

**Comment by retorquere** [comment]
I can see that. Speed is a reasonable goal for what Dijkstra is used for.

Are there benchmarks for this library against others?

**Comment by albertorestifo** [comment]
I didn't do any, not sure if somebody in the community did.

If you feel like doing them, feel free to open a PR to update the README with the results 👍

**Comment by retorquere** [comment]
I've gone for an internal implementation (https://github.com/retorquere/zotero-erdos/blob/master/content/dijkstra.ts)

**Comment by albertorestifo** [comment]
I'll close this issue given that I think find _all_ path will impact perforce of finding the shortest, and this library focuses on this last use-case.
