### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by mattdesl** [albertorestifo/node-dijkstra#5]
Since the new version relies on ES6, the module no longer works reliably in the browser or in older versions of Node. Is there any particular reason you decided not to pre-publish ES5 to npm?

**Comment by albertorestifo** [comment]
I never though about it's possible use in the browser, to be honest.

I sure can release a transpiled distribution, but I don't want it to be the main entry point. I will work on it.

**Comment by albertorestifo** [comment]
I've added the transpiled and minified versions: https://github.com/albertorestifo/node-dijkstra/tree/master/dist

Documentation and publication on NPM and Browserify to come. Keep in mind you will need the [Babel Polyfill](http://babeljs.io/docs/usage/polyfill/).

**Comment by albertorestifo** [comment]
I decided against publishing a browser-friendly copy of the library
