### ISSUE TITLE
Is it possible to remove a node?

### ISSUE THREAD

**Issue by keevitaja** [albertorestifo/node-dijkstra#8]
Is it possible to remove a node from graph?

**Comment by albertorestifo** [comment]
Not currently. But it's a nice addition to the library.

I'll try to work on in this week.

**Comment by albertorestifo** [comment]
Released with [`v2.3.0`](https://github.com/albertorestifo/node-dijkstra/releases/tag/v2.3.0) 😄

**Comment by barocsi** [comment]
Adding to this: is this possible to remove an edge?

**Comment by albertorestifo** [comment]
@barocsi there is no API to do that, however if you call `addNode` on the same node, it'll replace it.

```
graph.addNode('A', { B: 10, C: 20 });
```

Say you want to remove the edge C from A:

```
graph.addNode('A', { B: 10 });
```

Should do the trick.

**Comment by barocsi** [comment]
That works fine, thanks!

**Comment by barocsi** [comment]
Some additional and last question: how can I get a reference to a node by its key?
```
route.addNode('A', { B:1 })
route.addNode('B', { A:1, C:2, D: 4 })
route.addNode('C', { B:2, D:1 })
route.addNode('D', { C:1, B:4 })
```
for example before I modify the edges of A i need to get a hold of its current edges.

**Comment by barocsi** [comment]
Just found it,
route.graph.get('A')

**Comment by albertorestifo** [comment]
@barocsi beware of two things while doing that:

1. You're accessing and internal class property. If you don't treat the returned value as pure and accidentally modify it, you might have unexpected results.

1. The returned value will be a deep `Map`, not an object.

**Comment by barocsi** [comment]
Yes, and moreover its problematic. I tried to implement a path extraction from an existing graph by cloning the original. For some reason the original gets overridden, whilst, every reference is being reconstructed from scratch.
```
const Graph = require('node-dijkstra')
var route = new Graph()

function subtract(path, graph) {
    for (i = 0; i < path.length; i++) {

        // last item
        if (i == path.length - 1) {
            continue;
        }

        // current node
        var node_id = path[i];

        // connection to be removed
        var peer_id = path[i + 1];

        // load node
        var node = graph.graph.get(node_id);

        if (!node) {
            continue;
        }
        // delete edge (peer)
        node.delete(peer_id);
    }

}
function clonemap(map) {
    var newMap = new Map();
    map.forEach(function (value, key) {
        newMap.set(key, value);
    })
    return newMap;
}

route.addNode('A', {B: 1})
route.addNode('B', {A: 1, C: 2, D: 4})
route.addNode('C', {B: 2, D: 1})
route.addNode('D', {C: 1, B: 4})
console.log(route.path('A', 'D'))
var u = require('util');
console.log(u.inspect(route, {depth: 10}));
var route2 = new Graph(clonemap(route.graph));
console.log(u.inspect(route2, {depth: 10}));
subtract(['A', 'B', 'C', 'D'], route2)
console.log("------------original")
console.log(u.inspect(route, {depth: 10}));
console.log("------------new")
console.log(u.inspect(route2, {depth: 10}));
console.log(route.path('A', 'D')) // null
```
